---
- name: Save the kubeconfig ({{ acm_cluster_type }})
  ansible.builtin.copy:
    content: "{{ acm_kubeconfig_text }}"
    dest: "{{ dci_cluster_configs_dir }}/kubeconfig"
    mode: '0600'

- name: Save credentials ({{ acm_cluster_type }})
  ansible.builtin.copy:
    content: "{{ acm_cluster_type }} credentials\n
              ---\n
              username: {{ acm_kubeconfig_user }}\n
              password: {{ acm_kubeconfig_pass }}\n"
    dest: "{{ dci_cluster_configs_dir }}/kubeadmin-password"
    mode: '0600'
  no_log: true
...
