---
- name: Get cluster pull_secret
  kubernetes.core.k8s_info:
    api: v1
    kind: Secret
    name: "pull-secret"
    namespace: openshift-config
  register: hub_pull_secret
  retries: 3
  delay: 5
  until: "'resources' in hub_pull_secret and hub_pull_secret.resources != []"
  no_log: true

- name: Process extra pull secret file
  when:
    - pullsecret_file is defined
  block:
    - name: Check if the pullsecret_file file exists
      ansible.builtin.stat:
        path: "{{ pullsecret_file }}"
        get_checksum: false

    - name: Read the pull_secret_file in JSON format
      ansible.builtin.set_fact:
        ps_file: "{{ ( lookup('file', pullsecret_file | default({}) ) | from_json ) }}"
      no_log: true

- name: Combine auth files
  ansible.builtin.include_role:
    name: redhatci.ocp.merge_registry_creds
  vars:
    hub_ps: '{{ hub_pull_secret.resources[0].data[".dockerconfigjson"] | b64decode | from_json }}'
    mrc_auths: "{{ [ hub_ps, ps_file | default({}, True) ] }}"

- name: Set DCI pullsecrets
  ansible.builtin.set_fact:
    dci_pullsecret_file: "{{ mrc_auth_file }}"
    dci_pullsecret: "{{ mrc_auth_data }}"
  no_log: true
...
