---
- name: "Mirror OCP release 4.20.10 - OCPBUGS-86292"
  ansible.builtin.include_role:
    name: redhatci.ocp.mirror_ocp_release
  vars:
    mor_version: "4.20.10"
    mor_pull_url: "quay.io/openshift-release-dev/ocp-release:4.20.10-multi"
    mor_cache_dir: "{{ provision_cache_store | default((ansible_env.HOME, 'releases') | join('/')) }}"
    mor_webserver_url: "{{ hostvars.jumphost.webserver_url | default(None) }}"
    mor_registry_url: "{{ hub_registry | urlsplit('netloc') }}"
    mor_registry_path: "ocp-4.20/ocp-4.20.10"
    mor_auths_file: "{{ dci_pullsecret_file }}"
    mor_force: "{{ (dci_force_mirroring | default(false)) | bool }}"
    mor_install_type: "{{ (install_type | default('ipi')) }}"
    mor_mirror_disk_images: false
    mor_mirror_container_images: true
    mor_build: "ga"
    mor_oc: "{{ oc_tool_path }}"
    mor_extra_flags: "{{ dci_oc_mirror_extra_flags | default('') }}"

- name: Apply IDMS for 4.20.10 version to the Hub cluster
  vars:
    cache_dir: "{{ provision_cache_store | default((ansible_env.HOME, 'releases') | join('/')) }}"
  kubernetes.core.k8s:
    state: present
    src: "{{ cache_dir }}/4.20.10/imagesource.yaml"
