---
- name: Mirror ubi9 image for kernel sideloading
  when:
    - dci_sno_sideload_kernel_uri is defined
    - dci_sno_sideload_kernel_uri | length
    - (dci_disconnected | default(false) | bool) or
      (dci_local_registry is defined and dci_local_registry != '')
  block:
    - name: Mirror ubi9 image
      ansible.builtin.include_role:
        name: redhatci.ocp.mirror_images
      vars:
        mi_images:
          - registry.access.redhat.com/ubi9
        mi_authfile: "{{ dci_pullsecret_file }}"
        mi_registry: "{{ dci_local_registry }}"

    - name: Remove temporary Image Source file
      ansible.builtin.file:
        path: "{{ mi_is_file.path }}"
        state: absent
      when:
        - mi_is_file is defined
        - mi_is_file.path is defined
