---
- name: "Setup Minio instance"
  ansible.builtin.include_role:
    name: redhatci.ocp.setup_minio
  vars:
    sm_storage_class: "{{ minio_storage_class | default('ocs-storagecluster-cephfs') }}"
    sm_claim_size: "{{ minio_claim_size | default('10Gi') }}"
    sm_namespace: "{{ minio_namespace | default('minio') }}"
    sm_access_key_id: "{{ minio_access_key_id | default('minioadmin') }}"
    sm_access_key_secret: "{{ minio_access_key_secret | default('minioadmin') }}"
    sm_bucket_name: "{{ minio_bucket_name | default('loki') }}"
    sm_minio_client: "{{ minio_client_image }}"
    sm_minio_image: "{{ minio_image }}"
...
